blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/funchs/vscode-rebased/discussions
    about: Use Discussions for questions about how to do something with Rebased.
